// - LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN = 'LOGIN';
export const LOGIN_START = 'LOGIN_START';

// - LOGIN TOUR GUIDE
export const LOGIN_TOUR_GUIDE_SUCCESS = 'LOGIN_TOUR_GUIDE_SUCCESS';
export const LOGIN_TOUR_GUIDE_ERROR = 'LOGIN_TOUR_GUIDE_ERROR';
export const LOGIN_TOUR_GUIDE = 'LOGIN_TOUR_GUIDE';
export const LOGIN_TOUR_GUIDE_START = 'LOGIN_TOUR_GUIDE_START';

// - LOGOUT
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_START = 'LOGOUT_START';

// - LOGOUT TOUR GUIDE
export const LOGOUT_TOUR_GUIDE_SUCCESS = 'LOGOUT_TOUR_GUIDE_SUCCESS';
export const LOGOUT_TOUR_GUIDE_ERROR = 'LOGOUT_TOUR_GUIDE_ERROR';
export const LOGOUT_TOUR_GUIDE = 'LOGOUT_TOUR_GUIDE';
export const LOGOUT_TOUR_GUIDE_START = 'LOGOUT_TOUR_GUIDE_START';

//APPLICATION
export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_FONT = 'CHANGE_FONT';
export const FORCE_APPEARANCE = 'FORCE_APPEARANCE';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
export const CHANGE_TRAVEL = 'CHANGE_TRAVEL';
export const CHANGE_TOURGUIDE_LANGUAGE = 'CHANGE_TOURGUIDE_LANGUAGE';
export const CLEAR_TOURGUIDE_LANGUAGE = 'CLEAR_TOURGUIDE_LANGUAGE';

//EXPO-TOKEN-NOTIFICATION
export const ADD_TOKEN = 'ADD_TOKEN';
export const CLEAR_TOKEN = 'CLEAR_TOKEN';

//SWIPER-DATA
export const ADD_SWIPER = 'ADD_SWIPER';
export const CLEAR_SWIPER = 'CLEAR_SWIPER';

//TRAVEL-MODE
export const ADD_MODE = 'ADD_MODE';
export const CLEAR_MODE = 'CLEAR_MODE';